import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";
import PageTransition from "./components/shared/PageTransition";
import StairTransition from "./components/shared/StairTransition";
import { ThemeProvider } from "@/lib/theme-provider";
import "./globals.css";
import ChatbotButton from "./components/chatbot/ChatbotButton";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Satvik Sawhney",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jetbrainsMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Navbar />
          <StairTransition />
          <PageTransition>
          {children}
          </PageTransition>
          <Footer />
          <ChatbotButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
