import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";
import PageTransition from "./components/shared/PageTransition";
import "./globals.css";


const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Satvik Sawhney",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} antialiased`}
      >
        <Navbar />
        <PageTransition>
        {children}
        </PageTransition>
        <Footer />
      </body>
    </html>
  );
}
